name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install ninja-build clang -y
      - name: CMake
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
      - name: Build & Test
        run: cmake --build build && ctest --test-dir build
