name: Python Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest black flake8 isort coverage
          pip install -e .
      - name: Lint
        run: |
          black --check chess_ai scripts tests
          isort --check chess_ai scripts tests
          flake8 chess_ai scripts tests
      - name: Run tests with coverage
        run: pytest -q --cov=chess_ai --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v3
